### ISSUE TITLE
Add missing licensing information

### ISSUE THREAD

**Issue by JonLiuFYI** [trobanga/flutter_btleplug#1]
This template's `LICENSE` file is currently
```
TODO: Add your license here.
```
which isn't a license at all. That makes this template impossible to actually use because I (and other potential users) don't have the legal permission to use it for a project. [Having no license means that no one but the creator has rights.](https://www.gnu.org/licenses/license-list.en.html#NoLicense)

Please specify a valid license (or release into public domain) so others can legally use this template.

**Comment by trobanga** [comment]
It seems I forgot to push it...

Thanks :)
